FROM golang:alpine
ENV CGO_ENABLED=0

WORKDIR '/app'
COPY go.mod go.sum ./

RUN go mod download

COPY jjversion.go app_version.go ./
COPY jjvercore/*.go jjvercore/

CMD ["sh", "-c", "go vet && go test ./..."]
