name: devcontainer-ci
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
      - '.github/workflows/actions.yaml'
      - '.github/workflows/codeql-analysis.yaml'
      - '.github/dependabot.yaml'
    branches:
      - root
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
      - '.github/workflows/actions.yaml'
      - '.github/workflows/codeql-analysis.yaml'
      - '.github/dependabot.yaml'
  workflow_dispatch:

jobs:
  devcontainer-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: Setup Docker BuildKit
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
      - name: Build and run dev container task
        uses: devcontainers/ci@96af31b963e2ff6b5be0f96195a92f0c844c52b4
        with:
          imageName: ghcr.io/jjliggett/jjversion-dc
          runCmd: |
            echo "Starting"
            make test
            go vet
            go test ./...
            go build -o jjversion
            ./jjversion
            ./jjversion | jq --raw-output '.MajorMinorPatch'
            docker build -t jjliggett/jjversion .
            docker run -d --name jjversion jjliggett/jjversion sleep infinity
            docker cp . jjversion:/repo
            docker exec -t jjversion jjversion
            docker kill jjversion
            docker rm jjversion
          push: never
