name: devcontainer-ci
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
      - '.github/workflows/actions.yaml'
      - '.github/workflows/codeql-analysis.yaml'
      - '.github/dependabot.yaml'
      - '.gitignore'
    branches:
      - root
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
      - '.github/workflows/actions.yaml'
      - '.github/workflows/codeql-analysis.yaml'
      - '.github/dependabot.yaml'
      - '.gitignore'
  workflow_dispatch:

jobs:
  devcontainer-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - name: Setup Docker BuildKit
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3.2.0
      - name: Build and run dev container task
        uses: devcontainers/ci@7957e0cf6d027a8ab027745f399fcdbd3aa74f0f # v0.3.1900000348
        with:
          imageName: ghcr.io/jjliggett/jjversion-dc
          runCmd: |
            echo "Starting"
            make test
            go vet
            go test ./...
            go build -o jjversion
            ./jjversion
            ./jjversion | jq --raw-output '.MajorMinorPatch'
            docker build -t jjliggett/jjversion .
            docker run -d --name jjversion jjliggett/jjversion sleep infinity
            docker cp . jjversion:/repo
            docker exec -t jjversion jjversion
            docker kill jjversion
            docker rm jjversion
          push: never
