name: devcontainer-ci
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
      - '.github/workflows/actions.yaml'
      - '.github/workflows/codeql-analysis.yaml'
      - '.github/dependabot.yaml'
      - '.gitignore'
    branches:
      - root
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'docs/**'
      - '.github/workflows/actions.yaml'
      - '.github/workflows/codeql-analysis.yaml'
      - '.github/dependabot.yaml'
      - '.gitignore'
  workflow_dispatch:

jobs:
  devcontainer-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Docker BuildKit
        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3.11.0
      - name: Build and run dev container task
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          imageName: ghcr.io/jjliggett/jjversion-dc
          runCmd: |
            echo "Starting"
            make test
            go vet
            go test ./...
            go build -o jjversion
            ./jjversion
            ./jjversion | jq --raw-output '.MajorMinorPatch'
            docker build -t jjliggett/jjversion .
            docker run -d --name jjversion jjliggett/jjversion sleep infinity
            docker cp . jjversion:/repo
            docker exec -t jjversion jjversion
            docker kill jjversion
            docker rm jjversion
          push: never
